# Generated by Django 5.1.4 on 2026-07-15 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_candidature"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="candidatures_cv/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="CV",
            ),
        ),
    ]
