# Generated by Django 5.1.4 on 2026-07-15 13:54

import apps.memberships.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0003_candidature_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.memberships.models._cv_storage,
                upload_to="candidatures_cv/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="CV",
            ),
        ),
    ]
