# Generated by Django 5.1.4 on 2026-08-23 17:53

from django.db import migrations, models


def migrate_is_done_forward(apps, schema_editor):
    ProjectTask = apps.get_model("projects", "ProjectTask")
    ProjectTask.objects.filter(is_done=True).update(status="done")
    ProjectTask.objects.filter(is_done=False).update(status="todo")


def migrate_is_done_backward(apps, schema_editor):
    ProjectTask = apps.get_model("projects", "ProjectTask")
    ProjectTask.objects.filter(status="done").update(is_done=True)
    ProjectTask.objects.exclude(status="done").update(is_done=False)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "À faire"),
                    ("in_progress", "En cours"),
                    ("done", "Terminée"),
                    ("blocked", "Bloquée"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_is_done_forward, migrate_is_done_backward),
        migrations.RemoveField(
            model_name="projecttask",
            name="is_done",
        ),
    ]
