# Generated by Django 5.1.4 on 2026-07-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_email_from_user(apps, schema_editor):
    EventParticipant = apps.get_model("events", "EventParticipant")
    for participant in EventParticipant.objects.select_related("user").filter(user__isnull=False):
        participant.email = participant.user.email
        participant.first_name = participant.user.first_name
        participant.last_name = participant.user.last_name
        participant.save(update_fields=["email", "first_name", "last_name"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="event",
            name="recap_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/recap/",
                verbose_name="Image récapitulative",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_email_from_user, noop_reverse),
        migrations.AlterUniqueTogether(
            name="eventparticipant",
            unique_together={("event", "email")},
        ),
    ]
