# Generated by Django 5.1.4 on 2026-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_eventparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="nationality",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="organisation",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="profession",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="motivation",
            field=models.TextField(),
        ),
    ]
