# Generated by Django 5.1.4 on 2026-06-28 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cert_type",
                    models.CharField(
                        choices=[
                            ("participation", "Certificat de participation"),
                            ("formation", "Certificat de formation"),
                            ("competence", "Certificat de compétence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/qr/"
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat",
                "ordering": ["-issued_at"],
            },
        ),
    ]
