# Generated by Django 5.1.4 on 2026-08-23 15:26

from django.db import migrations, models

# Anciennes valeurs de "role" qui deviennent un "poste" (rôle -> membre).
POSTE_MAPPING = {
    "president": "president",
    "vp1": "vp1",
    "vp2": "vp2",
    "secretaire_general": "secretaire_general",
    "secretaire_general_adj": "secretaire_general_adj",
    "tresorier": "tresorier",
    "tresorier_adj": "tresorier_adj",
}
# Anciennes valeurs de "role" qui disparaissent purement et simplement (-> membre).
DROPPED_ROLES = {"formateur", "mentor", "responsable_departement"}


def migrate_roles_forward(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for old_role, poste in POSTE_MAPPING.items():
        User.objects.filter(role=old_role).update(role="membre", poste=poste)
    User.objects.filter(role__in=DROPPED_ROLES).update(role="membre")


def migrate_roles_backward(apps, schema_editor):
    # Perte d'information assumée (pas de données réelles à préserver) : on ne
    # tente pas de reconstituer les anciennes valeurs de role à partir de poste.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="poste",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "Président"),
                    ("vp1", "Vice-Président 1"),
                    ("vp2", "Vice-Président 2"),
                    ("secretaire_general", "Secrétaire Général"),
                    ("secretaire_general_adj", "Secrétaire Général Adjoint"),
                    ("tresorier", "Trésorier Général"),
                    ("tresorier_adj", "Trésorier Général Adjoint"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Poste au bureau",
            ),
        ),
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("responsable", "Responsable"),
                    ("membre", "Membre"),
                    ("candidat", "Candidat"),
                    ("visiteur", "Visiteur"),
                ],
                default="visiteur",
                max_length=30,
                verbose_name="Rôle",
            ),
        ),
    ]
