# Generated by Django 5.1.4 on 2026-07-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "departments",
            "0002_remove_department_head_remove_department_members_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Date de la séance")),
                (
                    "theme",
                    models.CharField(blank=True, max_length=300, verbose_name="Thème"),
                ),
                ("report", models.TextField(blank=True, verbose_name="Compte-rendu")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="departments.department",
                    ),
                ),
                (
                    "present_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attended_department_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Présents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance de département",
                "verbose_name_plural": "Séances de département",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "À faire"),
                            ("in_progress", "En cours"),
                            ("done", "Terminée"),
                            ("blocked", "Bloquée"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche de département",
                "verbose_name_plural": "Tâches de département",
                "ordering": ["-created_at"],
            },
        ),
    ]
