# Generated by Django 5.1.4 on 2026-07-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_departmentsession_departmenttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentsession",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("none", "Unique"),
                    ("weekly", "Hebdomadaire"),
                    ("biweekly", "Bihebdomadaire"),
                    ("monthly", "Mensuelle"),
                ],
                default="none",
                max_length=20,
                verbose_name="Fréquence",
            ),
        ),
        migrations.AddField(
            model_name="departmentsession",
            name="meet_link",
            field=models.URLField(blank=True, verbose_name="Lien de la réunion"),
        ),
        migrations.AddField(
            model_name="departmentsession",
            name="series_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="Série"
            ),
        ),
    ]
